# rust-toolchain.toml
# This configuration file specifies the Rust toolchain settings for the project.
# It includes the Rust channel, components, targets for cross-compilation, and the profile to be used.

[toolchain]
# Specify the Rust release channel.
# "stable" ensures stability and compatibility for production use.
channel = "1.78.0"

# Select the minimal profile.
# The minimal profile includes useful tools like `rustc`, `rust-std` and `cargo`.
# profile = "minimal"

# This profile will be used by rustup by default
# The default profile includes useful tools like `rustc`, `rust-std`, `cargo`, `rust-docs`, `rustfmt` and `clippy` 
profile = "default"

# List of components to be installed with the toolchain.
# These components enhance development productivity and tooling support.
components = [
  "rust-analyzer", # Provides advanced code analysis and IDE features.
  "rust-src",      # Includes the Rust source code, required by some tools and IDEs.
]

# Specify additional targets for cross-compilation.
# Add any target triples you require for your project.
# Example target triples include:
# - "wasm32-unknown-unknown" for WebAssembly
# - "x86_64-unknown-linux-gnu" for 64-bit Linux
# - "aarch64-apple-darwin" for ARM64 macOS
# targets = [ 
#   "wasm32-unknown-unknown", 
#   "aarch64-unknown-linux-gnu" 
# ]
